apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base

patchesStrategicMerge:
- config.yaml

nameSuffix: "2"

images:
- name: robinbaeckman/hopbox
  newName: robinbaeckman/hopbox
  newTag: 6fd4347041480814c96f

commonLabels:
  app.kubernetes.io/instance: hopbox2
  app.kubernetes.io/name: hopbox2
