apiVersion: 1
datasources:
  - name: Prometheus
    uid: prometheus
    access: proxy
    type: prometheus
    url: http://prometheus:9090
    isDefault: true
  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://loki:3100
    basicAuth: false
    editable: true
    jsonData:
      maxLines: 1000
      derivedFields:
        - name: TraceID
          datasourceUid: tempo
          matcherRegex: '"trace-id":"(\w+)'
          url: '$${__value.raw}'
        - name: 'profileID'
          datasourceUid: pyroscope
          #matcherRegex: "go_span_id=(\\w+)"
          matcherRegex: '"profile_id":"(\w+)'
          url: 'hopbox1.cpu{profile_id="$${__value.raw}"}'
          #url: '$${__value.raw}'

  - name: Tempo
    type: tempo
    uid: tempo
    url: http://tempo/
    access: proxy
    editable: true
    isDefault: false
    version: 1
    jsonData:
      httpMethod: GET
      tracesToLogs:
        datasourceUid: 'loki'
        tags: ['job', 'instance', 'pod', 'namespace', 'container']
        mapTagNamesEnabled: false
        spanEndTimeShift: '1h'
        filterByTraceID: false
        filterBySpanID: true
      serviceMap:
        datasourceUid: 'prometheus'
      search:
        hide: false
      nodeGraph:
        enabled: true
      lokiSearch:
        datasourceUid: 'loki'

  - name: Pyroscope
    uid: pyroscope
    type: pyroscope-datasource
    access: proxy
    orgId: 1
    jsonData:
      path: http://pyroscope:4040
