apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- config.yaml
- ingress.yaml
- namespace.yaml

namespace: omnifire

commonLabels:
  app.kubernetes.io/name: hopbox
