plugins:
- pyroscope-datasource
- pyroscope-panel
sidecar:
  image:
    repository: quay.io/kiwigrid/k8s-sidecar
    tag: 1.15.6
  dashboards:
    enabled: true
    label: grafana_dashboard
    folder: /tmp/dashboards
# use for downloadable dashboards which doesn't required modification
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: true
      editable: true
      options:
        path: /var/lib/grafana/dashboards/standarddashboards
dashboards:
  default:
    k8-node:
      gnetId: 12486
      datasource: Prometheus
    postgres:
      gnetId: 9628
      datasource: Prometheus
    k8-app:
      gnetId: 11143
      datasource: Prometheus
adminPassword: "secret"
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        uid: prometheus
        type: prometheus
        url: http://prometheus-server.observe.svc.cluster.local
        access: proxy
        isDefault: true
      - name: Postgres
        type: postgres
        url: postgresql.omnifire.svc.cluster.local:5432
        database: postgres
        user: postgres
        secureJsonData:
          password: 'secret'
        jsonData:
          sslmode: 'disable' # disable/require/verify-ca/verify-full
          maxOpenConns: 0 # Grafana v5.4+
          maxIdleConns: 2 # Grafana v5.4+
          connMaxLifetime: 14400 # Grafana v5.4+
          postgresVersion: 903 # 903=9.3, 904=9.4, 905=9.5, 906=9.6, 1000=10
          timescaledb: false
      - name: Tempo
        uid: tempo
        type: tempo
        url: http://tempo:3100
        access: proxy
        editable: true
        basicAuth: false
        isDefault: false
        version: 2
        jsonData:
          httpMethod: GET
          tracesToLogs:
            datasourceUid: 'loki'
            tags: ['job', 'instance', 'pod', 'namespace', 'app']
            mapTagNamesEnabled: false
            spanEndTimeShift: '1h'
            filterByTraceID: false
            filterBySpanID: true
          serviceMap:
            datasourceUid: 'prometheus'
          search:
            hide: false
          nodeGraph:
            enabled: true
          lokiSearch:
            datasourceUid: 'loki'
      - name: Loki
        uid: loki
        type: loki
        access: proxy
        url: http://loki-gateway
        basicAuth: false
        editable: true
        jsonData:
          maxLines: 1000
          derivedFields:
            - name: TraceID
              datasourceUid: tempo
              matcherRegex: '"traceID":"(\w+)'
              url: '$${__value.raw}'
            - name: 'profileID'
              datasourceUid: pyroscope
              #matcherRegex: "go_span_id=(\\w+)"
              matcherRegex: '"profileID":"(\w+)'
              #url: 'ride-sharing-app.cpu{profileID="$${__value.raw}"}'
              url: '$${__value.raw}'
      - name: Pyroscope
        uid: pyroscope
        type: pyroscope-datasource
        access: proxy
        orgId: 1
        jsonData:
          path: http://pyroscope:4040
