sidecar:
  image:
    repository: quay.io/kiwigrid/k8s-sidecar
    tag: 1.15.6
  dashboards:
    enabled: true
    label: grafana_dashboard
    folder: /tmp/dashboards
# use for downloadable dashboards which doesn't required modification
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: true
      editable: true
      options:
        path: /var/lib/grafana/dashboards/standarddashboards
dashboards:
  default:
    k8-node:
      gnetId: 12486
      datasource: Prometheus
    postgres:
      gnetId: 9628
      datasource: Prometheus
    k8-app:
      gnetId: 11143
      datasource: Prometheus
adminPassword: "secret"
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.observe.svc.cluster.local
        access: proxy
        isDefault: true
      - name: Postgres
        type: postgres
        url: postgresql.omnifire.svc.cluster.local:5432
        database: postgres
        user: postgres
        secureJsonData:
          password: 'secret'
        jsonData:
          sslmode: 'disable' # disable/require/verify-ca/verify-full
          maxOpenConns: 0 # Grafana v5.4+
          maxIdleConns: 2 # Grafana v5.4+
          connMaxLifetime: 14400 # Grafana v5.4+
          postgresVersion: 903 # 903=9.3, 904=9.4, 905=9.5, 906=9.6, 1000=10
          timescaledb: false
      - name: Tempo
        type: tempo
        access: proxy
        orgId: 1
        url: http://tempo:3100
        basicAuth: false
        isDefault: false
        version: 2
        editable: false
        apiVersion: 1
        uid: tempo
      - name: Loki
        type: loki
        url: http://loki-gateway
        jsonData:
          maxLines: 1000
          derivedFields:
          # Field with internal link pointing to data source in Grafana.
          # Right now, Grafana supports only Jaeger and Zipkin data sources as link targets.
          # datasourceUid value can be anything, but it should be unique across all defined data source uids.
          - datasourceUid: Tempo
            matcherRegex: '"traceID":"(\w+)'
            name: TraceID
            # url will be interpreted as query for the datasource
            url: '$${__value.raw}'
