FROM golang:1.20-alpine

WORKDIR /src

ENV VERSION=localdev CGO_ENABLED=0

COPY . .

WORKDIR hopbox

RUN go build --mod=vendor -ldflags="-w -s -X main.version=$VERSION" -o hopbox && \
	if [ ! -f env/config ]; then cp env/sample.config env/config ; fi

CMD ["sh", "-c", "./hopbox"]
