// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.12
// source: box/box.proto

package box

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Section int32

const (
	Section_SERVICE    Section = 0
	Section_STORAGE    Section = 1
	Section_MIDDLEWARE Section = 2
)

// Enum value maps for Section.
var (
	Section_name = map[int32]string{
		0: "SERVICE",
		1: "STORAGE",
		2: "MIDDLEWARE",
	}
	Section_value = map[string]int32{
		"SERVICE":    0,
		"STORAGE":    1,
		"MIDDLEWARE": 2,
	}
)

func (x Section) Enum() *Section {
	p := new(Section)
	*p = x
	return p
}

func (x Section) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Section) Descriptor() protoreflect.EnumDescriptor {
	return file_box_box_proto_enumTypes[0].Descriptor()
}

func (Section) Type() protoreflect.EnumType {
	return &file_box_box_proto_enumTypes[0]
}

func (x Section) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Section.Descriptor instead.
func (Section) EnumDescriptor() ([]byte, []int) {
	return file_box_box_proto_rawDescGZIP(), []int{0}
}

type Log struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enabled bool    `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Host    string  `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Section Section `protobuf:"varint,3,opt,name=section,proto3,enum=box.Section" json:"section,omitempty"`
}

func (x *Log) Reset() {
	*x = Log{}
	if protoimpl.UnsafeEnabled {
		mi := &file_box_box_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_box_box_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_box_box_proto_rawDescGZIP(), []int{0}
}

func (x *Log) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Log) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Log) GetSection() Section {
	if x != nil {
		return x.Section
	}
	return Section_SERVICE
}

type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enabled bool    `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Host    string  `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Section Section `protobuf:"varint,3,opt,name=section,proto3,enum=box.Section" json:"section,omitempty"`
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_box_box_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_box_box_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_box_box_proto_rawDescGZIP(), []int{1}
}

func (x *Error) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Error) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Error) GetSection() Section {
	if x != nil {
		return x.Section
	}
	return Section_SERVICE
}

type HopRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host    string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Persist bool   `protobuf:"varint,2,opt,name=persist,proto3" json:"persist,omitempty"`
	Data    string `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Error   *Error `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	Log     *Log   `protobuf:"bytes,5,opt,name=log,proto3" json:"log,omitempty"`
}

func (x *HopRequest) Reset() {
	*x = HopRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_box_box_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HopRequest) ProtoMessage() {}

func (x *HopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_box_box_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HopRequest.ProtoReflect.Descriptor instead.
func (*HopRequest) Descriptor() ([]byte, []int) {
	return file_box_box_proto_rawDescGZIP(), []int{2}
}

func (x *HopRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *HopRequest) GetPersist() bool {
	if x != nil {
		return x.Persist
	}
	return false
}

func (x *HopRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *HopRequest) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *HopRequest) GetLog() *Log {
	if x != nil {
		return x.Log
	}
	return nil
}

type HopResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response string `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *HopResponse) Reset() {
	*x = HopResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_box_box_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HopResponse) ProtoMessage() {}

func (x *HopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_box_box_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HopResponse.ProtoReflect.Descriptor instead.
func (*HopResponse) Descriptor() ([]byte, []int) {
	return file_box_box_proto_rawDescGZIP(), []int{3}
}

func (x *HopResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

var File_box_box_proto protoreflect.FileDescriptor

var file_box_box_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x62, 0x6f, 0x78, 0x2f, 0x62, 0x6f, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x62, 0x6f, 0x78, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x5b, 0x0a, 0x03, 0x4c, 0x6f, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x61,
	0x62, 0x6c, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x6e, 0x61, 0x62,
	0x6c, 0x65, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x07, 0x73, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x62, 0x6f, 0x78, 0x2e, 0x53,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22,
	0x5d, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x61, 0x62,
	0x6c, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c,
	0x65, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x07, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x62, 0x6f, 0x78, 0x2e, 0x53, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x8c,
	0x01, 0x0a, 0x0a, 0x48, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x70, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12,
	0x20, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a,
	0x2e, 0x62, 0x6f, 0x78, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x12, 0x1a, 0x0a, 0x03, 0x6c, 0x6f, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08,
	0x2e, 0x62, 0x6f, 0x78, 0x2e, 0x4c, 0x6f, 0x67, 0x52, 0x03, 0x6c, 0x6f, 0x67, 0x22, 0x29, 0x0a,
	0x0b, 0x48, 0x6f, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2a, 0x33, 0x0a, 0x07, 0x53, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x45, 0x52, 0x56, 0x49, 0x43, 0x45, 0x10, 0x00,
	0x12, 0x0b, 0x0a, 0x07, 0x53, 0x54, 0x4f, 0x52, 0x41, 0x47, 0x45, 0x10, 0x01, 0x12, 0x0e, 0x0a,
	0x0a, 0x4d, 0x49, 0x44, 0x44, 0x4c, 0x45, 0x57, 0x41, 0x52, 0x45, 0x10, 0x02, 0x32, 0x40, 0x0a,
	0x03, 0x42, 0x6f, 0x78, 0x12, 0x39, 0x0a, 0x03, 0x48, 0x6f, 0x70, 0x12, 0x0f, 0x2e, 0x62, 0x6f,
	0x78, 0x2e, 0x48, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x62,
	0x6f, 0x78, 0x2e, 0x48, 0x6f, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x0f,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x09, 0x22, 0x04, 0x2f, 0x68, 0x6f, 0x70, 0x3a, 0x01, 0x2a, 0x42,
	0x14, 0x5a, 0x12, 0x6f, 0x6d, 0x6e, 0x69, 0x66, 0x69, 0x72, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x62, 0x6f, 0x78, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_box_box_proto_rawDescOnce sync.Once
	file_box_box_proto_rawDescData = file_box_box_proto_rawDesc
)

func file_box_box_proto_rawDescGZIP() []byte {
	file_box_box_proto_rawDescOnce.Do(func() {
		file_box_box_proto_rawDescData = protoimpl.X.CompressGZIP(file_box_box_proto_rawDescData)
	})
	return file_box_box_proto_rawDescData
}

var file_box_box_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_box_box_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_box_box_proto_goTypes = []interface{}{
	(Section)(0),        // 0: box.Section
	(*Log)(nil),         // 1: box.Log
	(*Error)(nil),       // 2: box.Error
	(*HopRequest)(nil),  // 3: box.HopRequest
	(*HopResponse)(nil), // 4: box.HopResponse
}
var file_box_box_proto_depIdxs = []int32{
	0, // 0: box.Log.section:type_name -> box.Section
	0, // 1: box.Error.section:type_name -> box.Section
	2, // 2: box.HopRequest.error:type_name -> box.Error
	1, // 3: box.HopRequest.log:type_name -> box.Log
	3, // 4: box.Box.Hop:input_type -> box.HopRequest
	4, // 5: box.Box.Hop:output_type -> box.HopResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_box_box_proto_init() }
func file_box_box_proto_init() {
	if File_box_box_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_box_box_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Log); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_box_box_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_box_box_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HopRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_box_box_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HopResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_box_box_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_box_box_proto_goTypes,
		DependencyIndexes: file_box_box_proto_depIdxs,
		EnumInfos:         file_box_box_proto_enumTypes,
		MessageInfos:      file_box_box_proto_msgTypes,
	}.Build()
	File_box_box_proto = out.File
	file_box_box_proto_rawDesc = nil
	file_box_box_proto_goTypes = nil
	file_box_box_proto_depIdxs = nil
}
