// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.12
// source: hopbox/hopbox.proto

package hopbox

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Section int32

const (
	Section_SERVICE Section = 0
	Section_STORAGE Section = 1
)

// Enum value maps for Section.
var (
	Section_name = map[int32]string{
		0: "SERVICE",
		1: "STORAGE",
	}
	Section_value = map[string]int32{
		"SERVICE": 0,
		"STORAGE": 1,
	}
)

func (x Section) Enum() *Section {
	p := new(Section)
	*p = x
	return p
}

func (x Section) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Section) Descriptor() protoreflect.EnumDescriptor {
	return file_hopbox_hopbox_proto_enumTypes[0].Descriptor()
}

func (Section) Type() protoreflect.EnumType {
	return &file_hopbox_hopbox_proto_enumTypes[0]
}

func (x Section) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Section.Descriptor instead.
func (Section) EnumDescriptor() ([]byte, []int) {
	return file_hopbox_hopbox_proto_rawDescGZIP(), []int{0}
}

type Log struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hop     int32   `protobuf:"varint,1,opt,name=hop,proto3" json:"hop,omitempty"`
	Section Section `protobuf:"varint,2,opt,name=section,proto3,enum=hopbox.Section" json:"section,omitempty"`
	Data    string  `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Log) Reset() {
	*x = Log{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hopbox_hopbox_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_hopbox_hopbox_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_hopbox_hopbox_proto_rawDescGZIP(), []int{0}
}

func (x *Log) GetHop() int32 {
	if x != nil {
		return x.Hop
	}
	return 0
}

func (x *Log) GetSection() Section {
	if x != nil {
		return x.Section
	}
	return Section_SERVICE
}

func (x *Log) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hop     int32   `protobuf:"varint,1,opt,name=hop,proto3" json:"hop,omitempty"`
	Section Section `protobuf:"varint,2,opt,name=section,proto3,enum=hopbox.Section" json:"section,omitempty"`
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hopbox_hopbox_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_hopbox_hopbox_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_hopbox_hopbox_proto_rawDescGZIP(), []int{1}
}

func (x *Error) GetHop() int32 {
	if x != nil {
		return x.Hop
	}
	return 0
}

func (x *Error) GetSection() Section {
	if x != nil {
		return x.Section
	}
	return Section_SERVICE
}

type Work struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hop         int32 `protobuf:"varint,1,opt,name=hop,proto3" json:"hop,omitempty"`
	DurationSec int32 `protobuf:"varint,2,opt,name=durationSec,proto3" json:"durationSec,omitempty"`
}

func (x *Work) Reset() {
	*x = Work{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hopbox_hopbox_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Work) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Work) ProtoMessage() {}

func (x *Work) ProtoReflect() protoreflect.Message {
	mi := &file_hopbox_hopbox_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Work.ProtoReflect.Descriptor instead.
func (*Work) Descriptor() ([]byte, []int) {
	return file_hopbox_hopbox_proto_rawDescGZIP(), []int{2}
}

func (x *Work) GetHop() int32 {
	if x != nil {
		return x.Hop
	}
	return 0
}

func (x *Work) GetDurationSec() int32 {
	if x != nil {
		return x.DurationSec
	}
	return 0
}

type Persist struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hop  int32  `protobuf:"varint,1,opt,name=hop,proto3" json:"hop,omitempty"`
	Data string `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Persist) Reset() {
	*x = Persist{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hopbox_hopbox_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Persist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Persist) ProtoMessage() {}

func (x *Persist) ProtoReflect() protoreflect.Message {
	mi := &file_hopbox_hopbox_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Persist.ProtoReflect.Descriptor instead.
func (*Persist) Descriptor() ([]byte, []int) {
	return file_hopbox_hopbox_proto_rawDescGZIP(), []int{3}
}

func (x *Persist) GetHop() int32 {
	if x != nil {
		return x.Hop
	}
	return 0
}

func (x *Persist) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type HopRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Persist []*Persist `protobuf:"bytes,1,rep,name=persist,proto3" json:"persist,omitempty"`
	Error   *Error     `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Log     []*Log     `protobuf:"bytes,3,rep,name=log,proto3" json:"log,omitempty"`
	Work    *Work      `protobuf:"bytes,4,opt,name=work,proto3" json:"work,omitempty"`
}

func (x *HopRequest) Reset() {
	*x = HopRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hopbox_hopbox_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HopRequest) ProtoMessage() {}

func (x *HopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hopbox_hopbox_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HopRequest.ProtoReflect.Descriptor instead.
func (*HopRequest) Descriptor() ([]byte, []int) {
	return file_hopbox_hopbox_proto_rawDescGZIP(), []int{4}
}

func (x *HopRequest) GetPersist() []*Persist {
	if x != nil {
		return x.Persist
	}
	return nil
}

func (x *HopRequest) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *HopRequest) GetLog() []*Log {
	if x != nil {
		return x.Log
	}
	return nil
}

func (x *HopRequest) GetWork() *Work {
	if x != nil {
		return x.Work
	}
	return nil
}

type HopResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response string `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *HopResponse) Reset() {
	*x = HopResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hopbox_hopbox_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HopResponse) ProtoMessage() {}

func (x *HopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hopbox_hopbox_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HopResponse.ProtoReflect.Descriptor instead.
func (*HopResponse) Descriptor() ([]byte, []int) {
	return file_hopbox_hopbox_proto_rawDescGZIP(), []int{5}
}

func (x *HopResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

var File_hopbox_hopbox_proto protoreflect.FileDescriptor

var file_hopbox_hopbox_proto_rawDesc = []byte{
	0x0a, 0x13, 0x68, 0x6f, 0x70, 0x62, 0x6f, 0x78, 0x2f, 0x68, 0x6f, 0x70, 0x62, 0x6f, 0x78, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x68, 0x6f, 0x70, 0x62, 0x6f, 0x78, 0x1a, 0x1c, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x56, 0x0a, 0x03, 0x4c,
	0x6f, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x68, 0x6f, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x03, 0x68, 0x6f, 0x70, 0x12, 0x29, 0x0a, 0x07, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x68, 0x6f, 0x70, 0x62, 0x6f, 0x78, 0x2e, 0x53,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x44, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x10, 0x0a, 0x03,
	0x68, 0x6f, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x68, 0x6f, 0x70, 0x12, 0x29,
	0x0a, 0x07, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x0f, 0x2e, 0x68, 0x6f, 0x70, 0x62, 0x6f, 0x78, 0x2e, 0x53, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x07, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x3a, 0x0a, 0x04, 0x57, 0x6f, 0x72,
	0x6b, 0x12, 0x10, 0x0a, 0x03, 0x68, 0x6f, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x68, 0x6f, 0x70, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53,
	0x65, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x53, 0x65, 0x63, 0x22, 0x2f, 0x0a, 0x07, 0x50, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x68, 0x6f, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x68,
	0x6f, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x9d, 0x01, 0x0a, 0x0a, 0x48, 0x6f, 0x70, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x07, 0x70, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x68, 0x6f, 0x70, 0x62, 0x6f, 0x78, 0x2e,
	0x50, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x52, 0x07, 0x70, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74,
	0x12, 0x23, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x68, 0x6f, 0x70, 0x62, 0x6f, 0x78, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x1d, 0x0a, 0x03, 0x6c, 0x6f, 0x67, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x68, 0x6f, 0x70, 0x62, 0x6f, 0x78, 0x2e, 0x4c, 0x6f, 0x67, 0x52,
	0x03, 0x6c, 0x6f, 0x67, 0x12, 0x20, 0x0a, 0x04, 0x77, 0x6f, 0x72, 0x6b, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x68, 0x6f, 0x70, 0x62, 0x6f, 0x78, 0x2e, 0x57, 0x6f, 0x72, 0x6b,
	0x52, 0x04, 0x77, 0x6f, 0x72, 0x6b, 0x22, 0x29, 0x0a, 0x0b, 0x48, 0x6f, 0x70, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2a, 0x23, 0x0a, 0x07, 0x53, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0b, 0x0a, 0x07,
	0x53, 0x45, 0x52, 0x56, 0x49, 0x43, 0x45, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x54, 0x4f,
	0x52, 0x41, 0x47, 0x45, 0x10, 0x01, 0x32, 0x49, 0x0a, 0x06, 0x48, 0x6f, 0x70, 0x62, 0x6f, 0x78,
	0x12, 0x3f, 0x0a, 0x03, 0x48, 0x6f, 0x70, 0x12, 0x12, 0x2e, 0x68, 0x6f, 0x70, 0x62, 0x6f, 0x78,
	0x2e, 0x48, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x68, 0x6f,
	0x70, 0x62, 0x6f, 0x78, 0x2e, 0x48, 0x6f, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x0f, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x09, 0x22, 0x04, 0x2f, 0x68, 0x6f, 0x70, 0x3a, 0x01,
	0x2a, 0x42, 0x17, 0x5a, 0x15, 0x6f, 0x6d, 0x6e, 0x69, 0x66, 0x69, 0x72, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x68, 0x6f, 0x70, 0x62, 0x6f, 0x78, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_hopbox_hopbox_proto_rawDescOnce sync.Once
	file_hopbox_hopbox_proto_rawDescData = file_hopbox_hopbox_proto_rawDesc
)

func file_hopbox_hopbox_proto_rawDescGZIP() []byte {
	file_hopbox_hopbox_proto_rawDescOnce.Do(func() {
		file_hopbox_hopbox_proto_rawDescData = protoimpl.X.CompressGZIP(file_hopbox_hopbox_proto_rawDescData)
	})
	return file_hopbox_hopbox_proto_rawDescData
}

var file_hopbox_hopbox_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_hopbox_hopbox_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_hopbox_hopbox_proto_goTypes = []interface{}{
	(Section)(0),        // 0: hopbox.Section
	(*Log)(nil),         // 1: hopbox.Log
	(*Error)(nil),       // 2: hopbox.Error
	(*Work)(nil),        // 3: hopbox.Work
	(*Persist)(nil),     // 4: hopbox.Persist
	(*HopRequest)(nil),  // 5: hopbox.HopRequest
	(*HopResponse)(nil), // 6: hopbox.HopResponse
}
var file_hopbox_hopbox_proto_depIdxs = []int32{
	0, // 0: hopbox.Log.section:type_name -> hopbox.Section
	0, // 1: hopbox.Error.section:type_name -> hopbox.Section
	4, // 2: hopbox.HopRequest.persist:type_name -> hopbox.Persist
	2, // 3: hopbox.HopRequest.error:type_name -> hopbox.Error
	1, // 4: hopbox.HopRequest.log:type_name -> hopbox.Log
	3, // 5: hopbox.HopRequest.work:type_name -> hopbox.Work
	5, // 6: hopbox.Hopbox.Hop:input_type -> hopbox.HopRequest
	6, // 7: hopbox.Hopbox.Hop:output_type -> hopbox.HopResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_hopbox_hopbox_proto_init() }
func file_hopbox_hopbox_proto_init() {
	if File_hopbox_hopbox_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_hopbox_hopbox_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Log); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hopbox_hopbox_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hopbox_hopbox_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Work); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hopbox_hopbox_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Persist); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hopbox_hopbox_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HopRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hopbox_hopbox_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HopResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hopbox_hopbox_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hopbox_hopbox_proto_goTypes,
		DependencyIndexes: file_hopbox_hopbox_proto_depIdxs,
		EnumInfos:         file_hopbox_hopbox_proto_enumTypes,
		MessageInfos:      file_hopbox_hopbox_proto_msgTypes,
	}.Build()
	File_hopbox_hopbox_proto = out.File
	file_hopbox_hopbox_proto_rawDesc = nil
	file_hopbox_hopbox_proto_goTypes = nil
	file_hopbox_hopbox_proto_depIdxs = nil
}
